"""adding warning field

Revision ID: 309cf493a1e2
Revises: 8fdc843fc202
Create Date: 2022-10-20 10:25:05.014779

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '309cf493a1e2'
down_revision = '8fdc843fc202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_table_metadata', sa.Column('notice_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_table_metadata', 'notice_text')
    # ### end Alembic commands ###
